/**
 * Demo data for RouMi - 30 villages, 8 hospitals, 6 ambulances
 * Maharashtra rural region
 */

import type { GraphNode, RoadEdge, Hospital, Ambulance } from '../../engine/domain/types';

export const DEMO_NODES: GraphNode[] = [
  // Villages
  { id: 'v-01', lat: 19.05, lng: 73.95, type: 'village', name: 'Khadakwadi' },
  { id: 'v-02', lat: 19.12, lng: 74.05, type: 'village', name: 'Pimpalgaon' },
  { id: 'v-03', lat: 19.18, lng: 73.88, type: 'village', name: 'Shirur' },
  { id: 'v-04', lat: 19.22, lng: 74.15, type: 'village', name: 'Manchar' },
  { id: 'v-05', lat: 19.28, lng: 73.92, type: 'village', name: 'Narayangaon' },
  { id: 'v-06', lat: 19.35, lng: 74.08, type: 'village', name: 'Junnar' },
  { id: 'v-07', lat: 19.08, lng: 74.22, type: 'village', name: 'Otur' },
  { id: 'v-08', lat: 19.15, lng: 74.28, type: 'village', name: 'Ale' },
  { id: 'v-09', lat: 19.25, lng: 74.35, type: 'village', name: 'Bori' },
  { id: 'v-10', lat: 19.32, lng: 73.78, type: 'village', name: 'Khed' },
  { id: 'v-11', lat: 19.40, lng: 73.95, type: 'village', name: 'Chakan' },
  { id: 'v-12', lat: 19.42, lng: 74.18, type: 'village', name: 'Rajgurunagar' },
  { id: 'v-13', lat: 19.10, lng: 73.75, type: 'village', name: 'Malshej' },
  { id: 'v-14', lat: 19.20, lng: 73.65, type: 'village', name: 'Mur bad' },
  { id: 'v-15', lat: 19.30, lng: 74.42, type: 'village', name: 'Parner' },
  { id: 'v-16', lat: 19.38, lng: 74.30, type: 'village', name: 'Shikrapur' },
  { id: 'v-17', lat: 19.45, lng: 73.85, type: 'village', name: 'Talegaon' },
  { id: 'v-18', lat: 19.02, lng: 74.12, type: 'village', name: 'Vadgaon' },
  { id: 'v-19', lat: 19.48, lng: 74.05, type: 'village', name: 'Alandi' },
  { id: 'v-20', lat: 19.33, lng: 73.62, type: 'village', name: 'Kusumba' },
  { id: 'v-21', lat: 19.55, lng: 73.90, type: 'village', name: 'Lonavala Fringe' },
  { id: 'v-22', lat: 19.18, lng: 74.45, type: 'village', name: 'Supa' },
  // Hospitals
  { id: 'h-n1', lat: 19.10, lng: 74.00, type: 'hospital', name: 'RuralCare Primary - Manchar' },
  { id: 'h-n2', lat: 19.25, lng: 74.10, type: 'hospital', name: 'District Hospital - Junnar' },
  { id: 'h-n3', lat: 19.35, lng: 73.90, type: 'hospital', name: 'Govt Medical - Chakan' },
  { id: 'h-n4', lat: 19.15, lng: 74.30, type: 'hospital', name: 'Trauma Center - Ale' },
  { id: 'h-n5', lat: 19.40, lng: 74.20, type: 'hospital', name: 'Cardiac Institute - Rajgurunagar' },
  { id: 'h-n6', lat: 19.00, lng: 73.80, type: 'hospital', name: 'Maternal Care - Malshej' },
  { id: 'h-n7', lat: 19.45, lng: 74.00, type: 'hospital', name: 'Multi-Specialty - Alandi' },
  { id: 'h-n8', lat: 19.30, lng: 74.25, type: 'hospital', name: 'Emergency Hub - Parner Road' },
];

export const DEMO_EDGES: RoadEdge[] = [
  // Primary ring
  { id: 'v-01->h-n1', from: 'v-01', to: 'h-n1', travelTime: 12, distance: 8, status: 'open' },
  { id: 'h-n1->v-02', from: 'h-n1', to: 'v-02', travelTime: 8, distance: 6, status: 'open' },
  { id: 'v-02->v-04', from: 'v-02', to: 'v-04', travelTime: 15, distance: 11, status: 'open' },
  { id: 'v-04->h-n2', from: 'v-04', to: 'h-n2', travelTime: 10, distance: 7, status: 'open' },
  { id: 'h-n2->v-05', from: 'h-n2', to: 'v-05', travelTime: 12, distance: 9, status: 'open' },
  { id: 'v-05->h-n3', from: 'v-05', to: 'h-n3', travelTime: 18, distance: 13, status: 'open' },
  { id: 'h-n3->v-11', from: 'h-n3', to: 'v-11', travelTime: 14, distance: 10, status: 'open' },
  { id: 'v-11->h-n5', from: 'v-11', to: 'h-n5', travelTime: 20, distance: 15, status: 'open' },
  { id: 'h-n5->v-12', from: 'h-n5', to: 'v-12', travelTime: 9, distance: 6, status: 'open' },
  { id: 'v-12->h-n7', from: 'v-12', to: 'h-n7', travelTime: 16, distance: 12, status: 'open' },
  { id: 'h-n7->v-19', from: 'h-n7', to: 'v-19', travelTime: 11, distance: 8, status: 'open' },
  { id: 'v-19->v-17', from: 'v-19', to: 'v-17', travelTime: 13, distance: 9, status: 'open' },
  // Secondary connections
  { id: 'v-01->v-03', from: 'v-01', to: 'v-03', travelTime: 22, distance: 16, status: 'open' },
  { id: 'v-03->h-n1', from: 'v-03', to: 'h-n1', travelTime: 17, distance: 12, status: 'open' },
  { id: 'v-03->v-13', from: 'v-03', to: 'v-13', travelTime: 25, distance: 18, status: 'open' },
  { id: 'v-13->h-n6', from: 'v-13', to: 'h-n6', travelTime: 14, distance: 10, status: 'open' },
  { id: 'h-n6->v-14', from: 'h-n6', to: 'v-14', travelTime: 19, distance: 14, status: 'open' },
  { id: 'v-14->v-20', from: 'v-14', to: 'v-20', travelTime: 16, distance: 11, status: 'open' },
  { id: 'v-20->v-10', from: 'v-20', to: 'v-10', travelTime: 12, distance: 8, status: 'open' },
  { id: 'v-10->h-n3', from: 'v-10', to: 'h-n3', travelTime: 21, distance: 15, status: 'open' },
  { id: 'v-02->v-07', from: 'v-02', to: 'v-07', travelTime: 18, distance: 13, status: 'open' },
  { id: 'v-07->h-n4', from: 'v-07', to: 'h-n4', travelTime: 15, distance: 11, status: 'open' },
  { id: 'h-n4->v-08', from: 'h-n4', to: 'v-08', travelTime: 8, distance: 5, status: 'open' },
  { id: 'v-08->v-09', from: 'v-08', to: 'v-09', travelTime: 14, distance: 10, status: 'open' },
  { id: 'v-09->h-n8', from: 'v-09', to: 'h-n8', travelTime: 12, distance: 9, status: 'open' },
  { id: 'h-n8->v-15', from: 'h-n8', to: 'v-15', travelTime: 10, distance: 7, status: 'open' },
  { id: 'v-15->v-22', from: 'v-15', to: 'v-22', travelTime: 13, distance: 9, status: 'open' },
  { id: 'v-22->h-n4', from: 'v-22', to: 'h-n4', travelTime: 17, distance: 12, status: 'open' },
  { id: 'v-04->v-07', from: 'v-04', to: 'v-07', travelTime: 20, distance: 14, status: 'open' },
  { id: 'h-n2->h-n4', from: 'h-n2', to: 'h-n4', travelTime: 28, distance: 20, status: 'open' },
  { id: 'h-n2->h-n8', from: 'h-n2', to: 'h-n8', travelTime: 22, distance: 16, status: 'open' },
  { id: 'v-06->h-n2', from: 'v-06', to: 'h-n2', travelTime: 11, distance: 8, status: 'open' },
  { id: 'v-06->v-05', from: 'v-06', to: 'v-05', travelTime: 14, distance: 10, status: 'open' },
  { id: 'v-11->v-16', from: 'v-11', to: 'v-16', travelTime: 16, distance: 11, status: 'open' },
  { id: 'v-16->h-n5', from: 'v-16', to: 'h-n5', travelTime: 9, distance: 6, status: 'open' },
  { id: 'v-18->v-01', from: 'v-18', to: 'v-01', travelTime: 13, distance: 9, status: 'open' },
  { id: 'v-18->h-n1', from: 'v-18', to: 'h-n1', travelTime: 10, distance: 7, status: 'open' },
  { id: 'v-17->v-21', from: 'v-17', to: 'v-21', travelTime: 24, distance: 17, status: 'open' },
  { id: 'v-21->h-n6', from: 'v-21', to: 'h-n6', travelTime: 32, distance: 23, status: 'open' },
  { id: 'h-n3->h-n5', from: 'h-n3', to: 'h-n5', travelTime: 26, distance: 19, status: 'open' },
  { id: 'h-n7->h-n3', from: 'h-n7', to: 'h-n3', travelTime: 30, distance: 21, status: 'open' },
];

export const DEMO_HOSPITALS: Hospital[] = [
  {
    id: 'h-n1',
    nodeId: 'h-n1',
    name: 'RuralCare Primary - Manchar',
    specialists: ['General Surgeon', 'Pediatrician', 'Gynaecologist'],
    bedsTotal: 12,
    bedsAvailable: 8,
    bedsReserved: 0,
    medicines: {
      'Surgical Kit': { available: 15, reserved: 0, total: 15 },
      'Pediatric Serum': { available: 10, reserved: 0, total: 10 },
      'Oxytocin': { available: 12, reserved: 0, total: 12 },
    },
    status: 'operational',
  },
  {
    id: 'h-n2',
    nodeId: 'h-n2',
    name: 'District Hospital - Junnar',
    specialists: ['Cardiologist', 'Orthopedic', 'General Surgeon', 'Trauma Specialist'],
    bedsTotal: 20,
    bedsAvailable: 12,
    bedsReserved: 0,
    medicines: {
      'Cardiac Drug X': { available: 8, reserved: 0, total: 8 },
      'Ortho Kit': { available: 10, reserved: 0, total: 10 },
      'Surgical Kit': { available: 20, reserved: 0, total: 20 },
      'Trauma Pack': { available: 15, reserved: 0, total: 15 },
    },
    status: 'operational',
  },
  {
    id: 'h-n3',
    nodeId: 'h-n3',
    name: 'Govt Medical - Chakan',
    specialists: ['Neurologist', 'Pulmonologist', 'General Surgeon'],
    bedsTotal: 25,
    bedsAvailable: 15,
    bedsReserved: 0,
    medicines: {
      'Neuro Aid': { available: 12, reserved: 0, total: 12 },
      'Ventilator Support': { available: 6, reserved: 0, total: 6 },
      'Surgical Kit': { available: 18, reserved: 0, total: 18 },
    },
    status: 'operational',
  },
  {
    id: 'h-n4',
    nodeId: 'h-n4',
    name: 'Trauma Center - Ale',
    specialists: ['Trauma Specialist', 'Orthopedic', 'General Surgeon'],
    bedsTotal: 15,
    bedsAvailable: 9,
    bedsReserved: 0,
    medicines: {
      'Trauma Pack': { available: 20, reserved: 0, total: 20 },
      'Ortho Kit': { available: 12, reserved: 0, total: 12 },
      'Surgical Kit': { available: 15, reserved: 0, total: 15 },
    },
    status: 'operational',
  },
  {
    id: 'h-n5',
    nodeId: 'h-n5',
    name: 'Cardiac Institute - Rajgurunagar',
    specialists: ['Cardiologist', 'Pulmonologist'],
    bedsTotal: 18,
    bedsAvailable: 10,
    bedsReserved: 0,
    medicines: {
      'Cardiac Drug X': { available: 20, reserved: 0, total: 20 },
      'Ventilator Support': { available: 8, reserved: 0, total: 8 },
    },
    status: 'operational',
  },
  {
    id: 'h-n6',
    nodeId: 'h-n6',
    name: 'Maternal Care - Malshej',
    specialists: ['Gynaecologist', 'Pediatrician'],
    bedsTotal: 10,
    bedsAvailable: 6,
    bedsReserved: 0,
    medicines: {
      'Oxytocin': { available: 15, reserved: 0, total: 15 },
      'Pediatric Serum': { available: 12, reserved: 0, total: 12 },
    },
    status: 'operational',
  },
  {
    id: 'h-n7',
    nodeId: 'h-n7',
    name: 'Multi-Specialty - Alandi',
    specialists: ['Cardiologist', 'Neurologist', 'Orthopedic', 'General Surgeon', 'Pediatrician', 'Pulmonologist', 'Gynaecologist', 'Trauma Specialist'],
    bedsTotal: 30,
    bedsAvailable: 18,
    bedsReserved: 0,
    medicines: {
      'Cardiac Drug X': { available: 15, reserved: 0, total: 15 },
      'Neuro Aid': { available: 10, reserved: 0, total: 10 },
      'Ortho Kit': { available: 12, reserved: 0, total: 12 },
      'Pediatric Serum': { available: 10, reserved: 0, total: 10 },
      'Surgical Kit': { available: 20, reserved: 0, total: 20 },
      'Ventilator Support': { available: 10, reserved: 0, total: 10 },
      'Oxytocin': { available: 10, reserved: 0, total: 10 },
      'Trauma Pack': { available: 12, reserved: 0, total: 12 },
    },
    status: 'operational',
  },
  {
    id: 'h-n8',
    nodeId: 'h-n8',
    name: 'Emergency Hub - Parner Road',
    specialists: ['Trauma Specialist', 'Cardiologist', 'General Surgeon'],
    bedsTotal: 16,
    bedsAvailable: 10,
    bedsReserved: 0,
    medicines: {
      'Trauma Pack': { available: 18, reserved: 0, total: 18 },
      'Cardiac Drug X': { available: 8, reserved: 0, total: 8 },
      'Surgical Kit': { available: 14, reserved: 0, total: 14 },
    },
    status: 'operational',
  },
];

export const DEMO_AMBULANCES: Ambulance[] = [
  { id: 'AMB-01', nodeId: 'h-n1', baseNodeId: 'h-n1', status: 'AVAILABLE', currentRequestId: null },
  { id: 'AMB-02', nodeId: 'h-n2', baseNodeId: 'h-n2', status: 'AVAILABLE', currentRequestId: null },
  { id: 'AMB-03', nodeId: 'h-n3', baseNodeId: 'h-n3', status: 'AVAILABLE', currentRequestId: null },
  { id: 'AMB-04', nodeId: 'h-n5', baseNodeId: 'h-n5', status: 'AVAILABLE', currentRequestId: null },
  { id: 'AMB-05', nodeId: 'h-n7', baseNodeId: 'h-n7', status: 'AVAILABLE', currentRequestId: null },
  { id: 'AMB-06', nodeId: 'h-n4', baseNodeId: 'h-n4', status: 'AVAILABLE', currentRequestId: null },
];
